// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apiv1

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AddSubjectMemberRequestRole.
const (
	AddSubjectMemberRequestRoleContributor AddSubjectMemberRequestRole = "contributor"
	AddSubjectMemberRequestRoleLead        AddSubjectMemberRequestRole = "lead"
	AddSubjectMemberRequestRoleViewer      AddSubjectMemberRequestRole = "viewer"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusOk HealthResponseStatus = "ok"
)

// Defines values for RunDetailStatus.
const (
	RunDetailStatusArchived   RunDetailStatus = "archived"
	RunDetailStatusDone       RunDetailStatus = "done"
	RunDetailStatusDraft      RunDetailStatus = "draft"
	RunDetailStatusInProgress RunDetailStatus = "in_progress"
)

// Defines values for RunItemStatus.
const (
	RunItemStatusNa      RunItemStatus = "na"
	RunItemStatusNok     RunItemStatus = "nok"
	RunItemStatusOk      RunItemStatus = "ok"
	RunItemStatusPending RunItemStatus = "pending"
)

// Defines values for RunSummaryStatus.
const (
	RunSummaryStatusArchived   RunSummaryStatus = "archived"
	RunSummaryStatusDone       RunSummaryStatus = "done"
	RunSummaryStatusDraft      RunSummaryStatus = "draft"
	RunSummaryStatusInProgress RunSummaryStatus = "in_progress"
)

// Defines values for SubjectDetailVisibility.
const (
	SubjectDetailVisibilityNormal  SubjectDetailVisibility = "normal"
	SubjectDetailVisibilityPrivate SubjectDetailVisibility = "private"
)

// Defines values for SubjectMemberRole.
const (
	SubjectMemberRoleContributor SubjectMemberRole = "contributor"
	SubjectMemberRoleLead        SubjectMemberRole = "lead"
	SubjectMemberRoleViewer      SubjectMemberRole = "viewer"
)

// Defines values for SubjectSummaryVisibility.
const (
	SubjectSummaryVisibilityNormal  SubjectSummaryVisibility = "normal"
	SubjectSummaryVisibilityPrivate SubjectSummaryVisibility = "private"
)

// Defines values for SubjectWriteRequestVisibility.
const (
	Normal  SubjectWriteRequestVisibility = "normal"
	Private SubjectWriteRequestVisibility = "private"
)

// Defines values for UpdateRunItemRequestStatus.
const (
	Na      UpdateRunItemRequestStatus = "na"
	Nok     UpdateRunItemRequestStatus = "nok"
	Ok      UpdateRunItemRequestStatus = "ok"
	Pending UpdateRunItemRequestStatus = "pending"
)

// Defines values for ListRunsParamsStatus.
const (
	Done       ListRunsParamsStatus = "done"
	Draft      ListRunsParamsStatus = "draft"
	InProgress ListRunsParamsStatus = "in_progress"
	Overdue    ListRunsParamsStatus = "overdue"
)

// AddSubjectMemberRequest defines model for AddSubjectMemberRequest.
type AddSubjectMemberRequest struct {
	Email openapi_types.Email          `json:"email"`
	Role  *AddSubjectMemberRequestRole `json:"role,omitempty"`
}

// AddSubjectMemberRequestRole defines model for AddSubjectMemberRequest.Role.
type AddSubjectMemberRequestRole string

// AuthSuccessResponse defines model for AuthSuccessResponse.
type AuthSuccessResponse struct {
	CsrfToken string `json:"csrf_token"`

	// Redirect Chemin SPA post-login (org onboarding ou accueil)
	Redirect string `json:"redirect"`
	User     User   `json:"user"`
}

// BootstrapResponse defines model for BootstrapResponse.
type BootstrapResponse struct {
	Authenticated bool `json:"authenticated"`

	// CsrfToken Jeton CSRF à envoyer en header X-CSRF-Token sur les mutations
	CsrfToken string `json:"csrf_token"`

	// GithubOauthEnabled true si REVUES_GITHUB_CLIENT_ID/SECRET sont configurés
	GithubOauthEnabled bool `json:"github_oauth_enabled"`

	// Redirect Chemin SPA suggéré si déjà authentifié
	Redirect *string `json:"redirect,omitempty"`
	User     *User   `json:"user,omitempty"`
}

// CompleteRunRequest defines model for CompleteRunRequest.
type CompleteRunRequest struct {
	// ClosingNote Note de cloture optionnelle
	ClosingNote *string `json:"closing_note,omitempty"`
}

// CreateOrganizationRequest defines model for CreateOrganizationRequest.
type CreateOrganizationRequest struct {
	Name string `json:"name"`

	// Slug Optionnel — dérivé du nom si omis
	Slug *string `json:"slug,omitempty"`
}

// CreateRunRequest defines model for CreateRunRequest.
type CreateRunRequest struct {
	// DueDate Date YYYY-MM-DD optionnelle
	DueDate    *string `json:"due_date"`
	TemplateId int64   `json:"template_id"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorBody `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status État de santé
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus État de santé
type HealthResponseStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	CsrfToken string `json:"csrf_token"`
	User      User   `json:"user"`
}

// Organization defines model for Organization.
type Organization struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`

	// Role Rôle org (owner|admin|member)
	Role           string  `json:"role"`
	Slug           string  `json:"slug"`
	UiRunLabel     *string `json:"ui_run_label,omitempty"`
	UiSubjectLabel *string `json:"ui_subject_label,omitempty"`
}

// OrganizationActionResponse defines model for OrganizationActionResponse.
type OrganizationActionResponse struct {
	Organization Organization `json:"organization"`

	// Redirect Chemin SPA après action (accueil)
	Redirect string `json:"redirect"`
}

// OrganizationInvitation defines model for OrganizationInvitation.
type OrganizationInvitation struct {
	CreatedAt        string `json:"created_at"`
	Id               int64  `json:"id"`
	OrgRole          string `json:"org_role"`
	OrganizationId   int64  `json:"organization_id"`
	OrganizationName string `json:"organization_name"`
}

// OrganizationListResponse defines model for OrganizationListResponse.
type OrganizationListResponse struct {
	// ActiveOrganizationId Org active sur la session (null si pending)
	ActiveOrganizationId *int64 `json:"active_organization_id"`

	// CanCreate true si l'utilisateur n'a encore aucune appartenance
	CanCreate bool `json:"can_create"`

	// DefaultOrganizationId Suggestion depuis cookie revues_last_org si membre
	DefaultOrganizationId *int64                   `json:"default_organization_id"`
	Invitations           []OrganizationInvitation `json:"invitations"`
	Organizations         []Organization           `json:"organizations"`

	// Redirect Chemin SPA suggéré selon le nombre d'orgs
	Redirect *string `json:"redirect,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName     string              `json:"display_name"`
	Email           openapi_types.Email `json:"email"`
	Password        string              `json:"password"`
	PasswordConfirm string              `json:"password_confirm"`
}

// RunAssignee defines model for RunAssignee.
type RunAssignee struct {
	DisplayName string `json:"display_name"`
	Login       string `json:"login"`
	UserId      int64  `json:"user_id"`
}

// RunCapabilities defines model for RunCapabilities.
type RunCapabilities struct {
	CanAssign      bool `json:"can_assign"`
	CanComplete    bool `json:"can_complete"`
	CanUpdateItems bool `json:"can_update_items"`
}

// RunDetail defines model for RunDetail.
type RunDetail struct {
	Assignees            *[]RunAssignee  `json:"assignees,omitempty"`
	Capabilities         RunCapabilities `json:"capabilities"`
	ClosingNote          *string         `json:"closing_note,omitempty"`
	CompletedAt          *string         `json:"completed_at"`
	CreatedAt            string          `json:"created_at"`
	DueDate              *string         `json:"due_date"`
	Id                   int64           `json:"id"`
	Items                []RunItem       `json:"items"`
	PendingRequiredCount *int            `json:"pending_required_count,omitempty"`
	Progress             RunProgress     `json:"progress"`
	StartedAt            *string         `json:"started_at"`
	Status               RunDetailStatus `json:"status"`
	SubjectId            int64           `json:"subject_id"`
	SubjectName          string          `json:"subject_name"`
	TemplateId           int64           `json:"template_id"`
	TemplateName         string          `json:"template_name"`
	TemplateVersion      int             `json:"template_version"`
	Title                string          `json:"title"`
}

// RunDetailStatus defines model for RunDetail.Status.
type RunDetailStatus string

// RunItem defines model for RunItem.
type RunItem struct {
	AssignedLogin *string       `json:"assigned_login"`
	AssignedTo    *int64        `json:"assigned_to"`
	Comment       string        `json:"comment"`
	HelpText      *string       `json:"help_text,omitempty"`
	Id            int64         `json:"id"`
	Label         string        `json:"label"`
	Position      int           `json:"position"`
	Required      bool          `json:"required"`
	RunId         int64         `json:"run_id"`
	Section       string        `json:"section"`
	Status        RunItemStatus `json:"status"`
	UpdatedAt     string        `json:"updated_at"`
}

// RunItemStatus defines model for RunItem.Status.
type RunItemStatus string

// RunItemDetail defines model for RunItemDetail.
type RunItemDetail struct {
	Assignees    *[]RunAssignee  `json:"assignees,omitempty"`
	Capabilities RunCapabilities `json:"capabilities"`
	Events       []RunItemEvent  `json:"events"`
	Item         RunItem         `json:"item"`
	RunStatus    *string         `json:"run_status,omitempty"`
	RunTitle     *string         `json:"run_title,omitempty"`
	SubjectId    *int64          `json:"subject_id,omitempty"`
	SubjectName  *string         `json:"subject_name,omitempty"`
}

// RunItemEvent defines model for RunItemEvent.
type RunItemEvent struct {
	Comment   *string `json:"comment,omitempty"`
	CreatedAt string  `json:"created_at"`
	Id        int64   `json:"id"`
	NewStatus string  `json:"new_status"`
	OldStatus *string `json:"old_status"`
	UserLogin *string `json:"user_login"`
}

// RunListResponse defines model for RunListResponse.
type RunListResponse struct {
	Runs  []RunSummary `json:"runs"`
	Total int          `json:"total"`
}

// RunProgress defines model for RunProgress.
type RunProgress struct {
	Done    int `json:"done"`
	Percent int `json:"percent"`
	Total   int `json:"total"`
}

// RunSummary defines model for RunSummary.
type RunSummary struct {
	CompletedAt    *string          `json:"completed_at"`
	CreatedAt      string           `json:"created_at"`
	CreatedByLogin *string          `json:"created_by_login"`
	DueDate        *string          `json:"due_date"`
	Id             int64            `json:"id"`
	Progress       RunProgress      `json:"progress"`
	StartedAt      *string          `json:"started_at"`
	Status         RunSummaryStatus `json:"status"`
	SubjectId      int64            `json:"subject_id"`
	SubjectName    string           `json:"subject_name"`
	Title          string           `json:"title"`
}

// RunSummaryStatus defines model for RunSummary.Status.
type RunSummaryStatus string

// RunTemplateListResponse defines model for RunTemplateListResponse.
type RunTemplateListResponse struct {
	CanLaunch bool                 `json:"can_launch"`
	Templates []RunTemplateSummary `json:"templates"`
}

// RunTemplateSummary defines model for RunTemplateSummary.
type RunTemplateSummary struct {
	Domains       *[]string `json:"domains,omitempty"`
	Id            int64     `json:"id"`
	ItemCount     int       `json:"item_count"`
	LatestVersion int       `json:"latest_version"`
	Name          string    `json:"name"`
}

// SelectOrganizationRequest defines model for SelectOrganizationRequest.
type SelectOrganizationRequest struct {
	OrganizationId int64 `json:"organization_id"`
}

// SubjectAccessInfo defines model for SubjectAccessInfo.
type SubjectAccessInfo struct {
	// Role Rôle effectif (lead|contributor|viewer|"")
	Role string `json:"role"`

	// Sources Sources d'accès (direct, team:N, org_admin, …)
	Sources []string `json:"sources"`
}

// SubjectCapabilities defines model for SubjectCapabilities.
type SubjectCapabilities struct {
	// CanLaunch Lancer une revue (contributor+ effectif)
	CanLaunch bool `json:"can_launch"`

	// CanManage Modifier / archiver
	CanManage bool `json:"can_manage"`

	// CanManageMembers Inviter / retirer des membres directs
	CanManageMembers bool `json:"can_manage_members"`

	// CanSetVisibility Changer subjects.visibility
	CanSetVisibility bool `json:"can_set_visibility"`
}

// SubjectDetail defines model for SubjectDetail.
type SubjectDetail struct {
	Access       SubjectAccessInfo   `json:"access"`
	Capabilities SubjectCapabilities `json:"capabilities"`
	Description  string              `json:"description"`

	// Domains Domaines de matching modèles (pas d'accès)
	Domains []string        `json:"domains"`
	Id      int64           `json:"id"`
	Members []SubjectMember `json:"members"`
	Name    string          `json:"name"`

	// Tags Étiquettes descriptives (pas d'accès)
	Tags       []string                `json:"tags"`
	Visibility SubjectDetailVisibility `json:"visibility"`
}

// SubjectDetailVisibility defines model for SubjectDetail.Visibility.
type SubjectDetailVisibility string

// SubjectListResponse defines model for SubjectListResponse.
type SubjectListResponse struct {
	// CanCreate true si l'utilisateur peut créer un sujet (editor+)
	CanCreate bool             `json:"can_create"`
	Subjects  []SubjectSummary `json:"subjects"`
}

// SubjectMember defines model for SubjectMember.
type SubjectMember struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Login       string              `json:"login"`
	Role        SubjectMemberRole   `json:"role"`
	UserId      int64               `json:"user_id"`
}

// SubjectMemberRole defines model for SubjectMember.Role.
type SubjectMemberRole string

// SubjectMemberListResponse defines model for SubjectMemberListResponse.
type SubjectMemberListResponse struct {
	Members []SubjectMember `json:"members"`
}

// SubjectSummary defines model for SubjectSummary.
type SubjectSummary struct {
	Description string `json:"description"`
	Id          int64  `json:"id"`
	Name        string `json:"name"`

	// Visibility Visibilité sujet (private exige grant explicite)
	Visibility SubjectSummaryVisibility `json:"visibility"`
}

// SubjectSummaryVisibility Visibilité sujet (private exige grant explicite)
type SubjectSummaryVisibility string

// SubjectWriteRequest defines model for SubjectWriteRequest.
type SubjectWriteRequest struct {
	Description *string `json:"description,omitempty"`

	// Domains Domaines de matching (CSV côté legacy)
	Domains *[]string `json:"domains,omitempty"`
	Name    string    `json:"name"`
	Tags    *[]string `json:"tags,omitempty"`

	// Visibility Ignoré si CanSetSubjectVisibility est faux
	Visibility *SubjectWriteRequestVisibility `json:"visibility,omitempty"`
}

// SubjectWriteRequestVisibility Ignoré si CanSetSubjectVisibility est faux
type SubjectWriteRequestVisibility string

// TemplateDetail defines model for TemplateDetail.
type TemplateDetail struct {
	// CanManage true si l'utilisateur courant peut éditer/archiver
	CanManage *bool                  `json:"can_manage,omitempty"`
	CreatedAt string                 `json:"created_at"`
	Domains   []string               `json:"domains"`
	Id        int64                  `json:"id"`
	Items     []TemplateItem         `json:"items"`
	Name      string                 `json:"name"`
	Version   TemplateVersionSummary `json:"version"`
}

// TemplateItem defines model for TemplateItem.
type TemplateItem struct {
	HelpText string `json:"help_text"`
	Id       int64  `json:"id"`
	Label    string `json:"label"`
	Position int    `json:"position"`
	Required bool   `json:"required"`
	Section  string `json:"section"`
}

// TemplateItemInput defines model for TemplateItemInput.
type TemplateItemInput struct {
	// HelpText Texte d'aide optionnel
	HelpText *string `json:"help_text,omitempty"`

	// Label Libellé du point
	Label string `json:"label"`

	// Required Point obligatoire à la revue
	Required *bool `json:"required,omitempty"`

	// Section Titre de section (optionnel)
	Section *string `json:"section,omitempty"`
}

// TemplateListResponse defines model for TemplateListResponse.
type TemplateListResponse struct {
	Templates []TemplateSummary `json:"templates"`
}

// TemplateSummary defines model for TemplateSummary.
type TemplateSummary struct {
	CreatedAt     string   `json:"created_at"`
	Domains       []string `json:"domains"`
	Id            int64    `json:"id"`
	ItemCount     int      `json:"item_count"`
	LatestVersion int      `json:"latest_version"`
	Name          string   `json:"name"`
}

// TemplateVersionCreateRequest defines model for TemplateVersionCreateRequest.
type TemplateVersionCreateRequest struct {
	Items []TemplateItemInput `json:"items"`
}

// TemplateVersionListResponse defines model for TemplateVersionListResponse.
type TemplateVersionListResponse struct {
	Versions []TemplateVersionSummary `json:"versions"`
}

// TemplateVersionSummary defines model for TemplateVersionSummary.
type TemplateVersionSummary struct {
	CreatedBy *int64 `json:"created_by"`
	Id        int64  `json:"id"`

	// PublishedAt Horodatage ISO 8601 UTC de publication
	PublishedAt string `json:"published_at"`
	Version     int    `json:"version"`
}

// TemplateWriteRequest defines model for TemplateWriteRequest.
type TemplateWriteRequest struct {
	// Domains Domaines de matching sujets (vide = tous)
	Domains *[]string           `json:"domains,omitempty"`
	Items   []TemplateItemInput `json:"items"`
	Name    string              `json:"name"`
}

// UpdateRunItemRequest defines model for UpdateRunItemRequest.
type UpdateRunItemRequest struct {
	// AssignedTo Assignee user id (omit = no change)
	AssignedTo *int64                      `json:"assigned_to,omitempty"`
	Comment    *string                     `json:"comment,omitempty"`
	Status     *UpdateRunItemRequestStatus `json:"status,omitempty"`

	// Unassign true to clear assignee (takes precedence over assigned_to)
	Unassign *bool `json:"unassign,omitempty"`
}

// UpdateRunItemRequestStatus defines model for UpdateRunItemRequest.Status.
type UpdateRunItemRequestStatus string

// User defines model for User.
type User struct {
	AvatarUrl   *string             `json:"avatar_url,omitempty"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          int64               `json:"id"`
	Login       string              `json:"login"`

	// Role Rôle global (admin|editor|reader)
	Role string `json:"role"`
}

// RunId defines model for RunId.
type RunId = int64

// RunItemId defines model for RunItemId.
type RunItemId = int64

// SubjectId defines model for SubjectId.
type SubjectId = int64

// TemplateId defines model for TemplateId.
type TemplateId = int64

// TemplateVersionNumber defines model for TemplateVersionNumber.
type TemplateVersionNumber = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListRunsParams defines parameters for ListRuns.
type ListRunsParams struct {
	// Status Filtre statut
	Status *ListRunsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Q Recherche texte
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRunsParamsStatus defines parameters for ListRuns.
type ListRunsParamsStatus string

// ListSubjectsParams defines parameters for ListSubjects.
type ListSubjectsParams struct {
	// Q Filtre texte (nom / description)
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// ListTemplatesParams defines parameters for ListTemplates.
type ListTemplatesParams struct {
	// Q Filtre texte (nom / domaines)
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody = CreateOrganizationRequest

// SelectActiveOrganizationJSONRequestBody defines body for SelectActiveOrganization for application/json ContentType.
type SelectActiveOrganizationJSONRequestBody = SelectOrganizationRequest

// CompleteRunJSONRequestBody defines body for CompleteRun for application/json ContentType.
type CompleteRunJSONRequestBody = CompleteRunRequest

// UpdateRunItemJSONRequestBody defines body for UpdateRunItem for application/json ContentType.
type UpdateRunItemJSONRequestBody = UpdateRunItemRequest

// CreateSubjectJSONRequestBody defines body for CreateSubject for application/json ContentType.
type CreateSubjectJSONRequestBody = SubjectWriteRequest

// UpdateSubjectJSONRequestBody defines body for UpdateSubject for application/json ContentType.
type UpdateSubjectJSONRequestBody = SubjectWriteRequest

// AddSubjectMemberJSONRequestBody defines body for AddSubjectMember for application/json ContentType.
type AddSubjectMemberJSONRequestBody = AddSubjectMemberRequest

// CreateRunJSONRequestBody defines body for CreateRun for application/json ContentType.
type CreateRunJSONRequestBody = CreateRunRequest

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = TemplateWriteRequest

// SaveTemplateJSONRequestBody defines body for SaveTemplate for application/json ContentType.
type SaveTemplateJSONRequestBody = TemplateWriteRequest

// CreateTemplateVersionJSONRequestBody defines body for CreateTemplateVersion for application/json ContentType.
type CreateTemplateVersionJSONRequestBody = TemplateVersionCreateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Connexion email + mot de passe
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Déconnexion
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// Inscription email + mot de passe
	// (POST /auth/register)
	PostAuthRegister(w http.ResponseWriter, r *http.Request)
	// Bootstrap session + CSRF
	// (GET /bootstrap)
	GetBootstrap(w http.ResponseWriter, r *http.Request)
	// Santé de l'API versionnée
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Utilisateur authentifié courant
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Organisations de l'utilisateur
	// (GET /orgs)
	ListOrganizations(w http.ResponseWriter, r *http.Request)
	// Créer une organisation (onboarding)
	// (POST /orgs)
	CreateOrganization(w http.ResponseWriter, r *http.Request)
	// Sélectionner / basculer l'organisation active
	// (POST /orgs/active)
	SelectActiveOrganization(w http.ResponseWriter, r *http.Request)
	// Accepter une invitation d'organisation
	// (POST /orgs/invitations/{invitationID}/accept)
	AcceptOrganizationInvitation(w http.ResponseWriter, r *http.Request, invitationID int64)
	// Liste des revues visibles
	// (GET /runs)
	ListRuns(w http.ResponseWriter, r *http.Request, params ListRunsParams)
	// Detail revue + items + progression
	// (GET /runs/{runId})
	GetRun(w http.ResponseWriter, r *http.Request, runId RunId)
	// Cloturer une revue
	// (POST /runs/{runId}/complete)
	CompleteRun(w http.ResponseWriter, r *http.Request, runId RunId)
	// Detail d'un point + audit
	// (GET /runs/{runId}/items/{itemId})
	GetRunItem(w http.ResponseWriter, r *http.Request, runId RunId, itemId RunItemId)
	// Mettre a jour status/comment/assign
	// (PATCH /runs/{runId}/items/{itemId})
	UpdateRunItem(w http.ResponseWriter, r *http.Request, runId RunId, itemId RunItemId)
	// Liste des sujets de l'org active
	// (GET /subjects)
	ListSubjects(w http.ResponseWriter, r *http.Request, params ListSubjectsParams)
	// Créer un sujet
	// (POST /subjects)
	CreateSubject(w http.ResponseWriter, r *http.Request)
	// Détail d'un sujet
	// (GET /subjects/{subjectId})
	GetSubject(w http.ResponseWriter, r *http.Request, subjectId SubjectId)
	// Modifier un sujet
	// (PATCH /subjects/{subjectId})
	UpdateSubject(w http.ResponseWriter, r *http.Request, subjectId SubjectId)
	// Archiver un sujet
	// (POST /subjects/{subjectId}/archive)
	ArchiveSubject(w http.ResponseWriter, r *http.Request, subjectId SubjectId)
	// Membres directs du sujet
	// (GET /subjects/{subjectId}/members)
	ListSubjectMembers(w http.ResponseWriter, r *http.Request, subjectId SubjectId)
	// Ajouter un membre direct
	// (POST /subjects/{subjectId}/members)
	AddSubjectMember(w http.ResponseWriter, r *http.Request, subjectId SubjectId)
	// Retirer un membre direct
	// (DELETE /subjects/{subjectId}/members/{userId})
	RemoveSubjectMember(w http.ResponseWriter, r *http.Request, subjectId SubjectId, userId int64)
	// Modeles lanables pour un sujet
	// (GET /subjects/{subjectId}/run-templates)
	ListSubjectRunTemplates(w http.ResponseWriter, r *http.Request, subjectId SubjectId)
	// Revues d'un sujet
	// (GET /subjects/{subjectId}/runs)
	ListSubjectRuns(w http.ResponseWriter, r *http.Request, subjectId SubjectId)
	// Lancer une revue (snapshot transactionnel)
	// (POST /subjects/{subjectId}/runs)
	CreateRun(w http.ResponseWriter, r *http.Request, subjectId SubjectId)
	// Catalogue des modèles
	// (GET /templates)
	ListTemplates(w http.ResponseWriter, r *http.Request, params ListTemplatesParams)
	// Créer un modèle (version 1)
	// (POST /templates)
	CreateTemplate(w http.ResponseWriter, r *http.Request)
	// Archiver un modèle
	// (DELETE /templates/{templateId})
	ArchiveTemplate(w http.ResponseWriter, r *http.Request, templateId TemplateId)
	// Détail modèle (dernière version)
	// (GET /templates/{templateId})
	GetTemplate(w http.ResponseWriter, r *http.Request, templateId TemplateId)
	// Enregistrer (nouvelle version)
	// (PUT /templates/{templateId})
	SaveTemplate(w http.ResponseWriter, r *http.Request, templateId TemplateId)
	// Historique des versions
	// (GET /templates/{templateId}/versions)
	ListTemplateVersions(w http.ResponseWriter, r *http.Request, templateId TemplateId)
	// Publier une nouvelle version
	// (POST /templates/{templateId}/versions)
	CreateTemplateVersion(w http.ResponseWriter, r *http.Request, templateId TemplateId)
	// Snapshot d'une version publiée
	// (GET /templates/{templateId}/versions/{version})
	GetTemplateVersion(w http.ResponseWriter, r *http.Request, templateId TemplateId, version TemplateVersionNumber)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Connexion email + mot de passe
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Déconnexion
// (POST /auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Inscription email + mot de passe
// (POST /auth/register)
func (_ Unimplemented) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Bootstrap session + CSRF
// (GET /bootstrap)
func (_ Unimplemented) GetBootstrap(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Santé de l'API versionnée
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Utilisateur authentifié courant
// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Organisations de l'utilisateur
// (GET /orgs)
func (_ Unimplemented) ListOrganizations(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Créer une organisation (onboarding)
// (POST /orgs)
func (_ Unimplemented) CreateOrganization(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Sélectionner / basculer l'organisation active
// (POST /orgs/active)
func (_ Unimplemented) SelectActiveOrganization(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Accepter une invitation d'organisation
// (POST /orgs/invitations/{invitationID}/accept)
func (_ Unimplemented) AcceptOrganizationInvitation(w http.ResponseWriter, r *http.Request, invitationID int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liste des revues visibles
// (GET /runs)
func (_ Unimplemented) ListRuns(w http.ResponseWriter, r *http.Request, params ListRunsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Detail revue + items + progression
// (GET /runs/{runId})
func (_ Unimplemented) GetRun(w http.ResponseWriter, r *http.Request, runId RunId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cloturer une revue
// (POST /runs/{runId}/complete)
func (_ Unimplemented) CompleteRun(w http.ResponseWriter, r *http.Request, runId RunId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Detail d'un point + audit
// (GET /runs/{runId}/items/{itemId})
func (_ Unimplemented) GetRunItem(w http.ResponseWriter, r *http.Request, runId RunId, itemId RunItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Mettre a jour status/comment/assign
// (PATCH /runs/{runId}/items/{itemId})
func (_ Unimplemented) UpdateRunItem(w http.ResponseWriter, r *http.Request, runId RunId, itemId RunItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liste des sujets de l'org active
// (GET /subjects)
func (_ Unimplemented) ListSubjects(w http.ResponseWriter, r *http.Request, params ListSubjectsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Créer un sujet
// (POST /subjects)
func (_ Unimplemented) CreateSubject(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Détail d'un sujet
// (GET /subjects/{subjectId})
func (_ Unimplemented) GetSubject(w http.ResponseWriter, r *http.Request, subjectId SubjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Modifier un sujet
// (PATCH /subjects/{subjectId})
func (_ Unimplemented) UpdateSubject(w http.ResponseWriter, r *http.Request, subjectId SubjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Archiver un sujet
// (POST /subjects/{subjectId}/archive)
func (_ Unimplemented) ArchiveSubject(w http.ResponseWriter, r *http.Request, subjectId SubjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Membres directs du sujet
// (GET /subjects/{subjectId}/members)
func (_ Unimplemented) ListSubjectMembers(w http.ResponseWriter, r *http.Request, subjectId SubjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Ajouter un membre direct
// (POST /subjects/{subjectId}/members)
func (_ Unimplemented) AddSubjectMember(w http.ResponseWriter, r *http.Request, subjectId SubjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retirer un membre direct
// (DELETE /subjects/{subjectId}/members/{userId})
func (_ Unimplemented) RemoveSubjectMember(w http.ResponseWriter, r *http.Request, subjectId SubjectId, userId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Modeles lanables pour un sujet
// (GET /subjects/{subjectId}/run-templates)
func (_ Unimplemented) ListSubjectRunTemplates(w http.ResponseWriter, r *http.Request, subjectId SubjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revues d'un sujet
// (GET /subjects/{subjectId}/runs)
func (_ Unimplemented) ListSubjectRuns(w http.ResponseWriter, r *http.Request, subjectId SubjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Lancer une revue (snapshot transactionnel)
// (POST /subjects/{subjectId}/runs)
func (_ Unimplemented) CreateRun(w http.ResponseWriter, r *http.Request, subjectId SubjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Catalogue des modèles
// (GET /templates)
func (_ Unimplemented) ListTemplates(w http.ResponseWriter, r *http.Request, params ListTemplatesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Créer un modèle (version 1)
// (POST /templates)
func (_ Unimplemented) CreateTemplate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Archiver un modèle
// (DELETE /templates/{templateId})
func (_ Unimplemented) ArchiveTemplate(w http.ResponseWriter, r *http.Request, templateId TemplateId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Détail modèle (dernière version)
// (GET /templates/{templateId})
func (_ Unimplemented) GetTemplate(w http.ResponseWriter, r *http.Request, templateId TemplateId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Enregistrer (nouvelle version)
// (PUT /templates/{templateId})
func (_ Unimplemented) SaveTemplate(w http.ResponseWriter, r *http.Request, templateId TemplateId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Historique des versions
// (GET /templates/{templateId}/versions)
func (_ Unimplemented) ListTemplateVersions(w http.ResponseWriter, r *http.Request, templateId TemplateId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Publier une nouvelle version
// (POST /templates/{templateId}/versions)
func (_ Unimplemented) CreateTemplateVersion(w http.ResponseWriter, r *http.Request, templateId TemplateId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Snapshot d'une version publiée
// (GET /templates/{templateId}/versions/{version})
func (_ Unimplemented) GetTemplateVersion(w http.ResponseWriter, r *http.Request, templateId TemplateId, version TemplateVersionNumber) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBootstrap operation middleware
func (siw *ServerInterfaceWrapper) GetBootstrap(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBootstrap(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrganizations operation middleware
func (siw *ServerInterfaceWrapper) ListOrganizations(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrganizations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrganization operation middleware
func (siw *ServerInterfaceWrapper) CreateOrganization(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrganization(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SelectActiveOrganization operation middleware
func (siw *ServerInterfaceWrapper) SelectActiveOrganization(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SelectActiveOrganization(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptOrganizationInvitation operation middleware
func (siw *ServerInterfaceWrapper) AcceptOrganizationInvitation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "invitationID" -------------
	var invitationID int64

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", chi.URLParam(r, "invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "invitationID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptOrganizationInvitation(w, r, invitationID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRuns operation middleware
func (siw *ServerInterfaceWrapper) ListRuns(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRunsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRuns(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteRun operation middleware
func (siw *ServerInterfaceWrapper) CompleteRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRunItem operation middleware
func (siw *ServerInterfaceWrapper) GetRunItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId RunItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRunItem(w, r, runId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRunItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateRunItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId RunItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRunItem(w, r, runId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSubjects operation middleware
func (siw *ServerInterfaceWrapper) ListSubjects(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSubjectsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSubjects(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSubject operation middleware
func (siw *ServerInterfaceWrapper) CreateSubject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSubject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubject operation middleware
func (siw *ServerInterfaceWrapper) GetSubject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subjectId" -------------
	var subjectId SubjectId

	err = runtime.BindStyledParameterWithOptions("simple", "subjectId", chi.URLParam(r, "subjectId"), &subjectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subjectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubject(w, r, subjectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSubject operation middleware
func (siw *ServerInterfaceWrapper) UpdateSubject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subjectId" -------------
	var subjectId SubjectId

	err = runtime.BindStyledParameterWithOptions("simple", "subjectId", chi.URLParam(r, "subjectId"), &subjectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subjectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSubject(w, r, subjectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ArchiveSubject operation middleware
func (siw *ServerInterfaceWrapper) ArchiveSubject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subjectId" -------------
	var subjectId SubjectId

	err = runtime.BindStyledParameterWithOptions("simple", "subjectId", chi.URLParam(r, "subjectId"), &subjectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subjectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ArchiveSubject(w, r, subjectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSubjectMembers operation middleware
func (siw *ServerInterfaceWrapper) ListSubjectMembers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subjectId" -------------
	var subjectId SubjectId

	err = runtime.BindStyledParameterWithOptions("simple", "subjectId", chi.URLParam(r, "subjectId"), &subjectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subjectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSubjectMembers(w, r, subjectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddSubjectMember operation middleware
func (siw *ServerInterfaceWrapper) AddSubjectMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subjectId" -------------
	var subjectId SubjectId

	err = runtime.BindStyledParameterWithOptions("simple", "subjectId", chi.URLParam(r, "subjectId"), &subjectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subjectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddSubjectMember(w, r, subjectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveSubjectMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveSubjectMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subjectId" -------------
	var subjectId SubjectId

	err = runtime.BindStyledParameterWithOptions("simple", "subjectId", chi.URLParam(r, "subjectId"), &subjectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subjectId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId int64

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveSubjectMember(w, r, subjectId, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSubjectRunTemplates operation middleware
func (siw *ServerInterfaceWrapper) ListSubjectRunTemplates(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subjectId" -------------
	var subjectId SubjectId

	err = runtime.BindStyledParameterWithOptions("simple", "subjectId", chi.URLParam(r, "subjectId"), &subjectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subjectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSubjectRunTemplates(w, r, subjectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSubjectRuns operation middleware
func (siw *ServerInterfaceWrapper) ListSubjectRuns(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subjectId" -------------
	var subjectId SubjectId

	err = runtime.BindStyledParameterWithOptions("simple", "subjectId", chi.URLParam(r, "subjectId"), &subjectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subjectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSubjectRuns(w, r, subjectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRun operation middleware
func (siw *ServerInterfaceWrapper) CreateRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subjectId" -------------
	var subjectId SubjectId

	err = runtime.BindStyledParameterWithOptions("simple", "subjectId", chi.URLParam(r, "subjectId"), &subjectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subjectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRun(w, r, subjectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTemplates operation middleware
func (siw *ServerInterfaceWrapper) ListTemplates(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTemplatesParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTemplates(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTemplate operation middleware
func (siw *ServerInterfaceWrapper) CreateTemplate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ArchiveTemplate operation middleware
func (siw *ServerInterfaceWrapper) ArchiveTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId TemplateId

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", chi.URLParam(r, "templateId"), &templateId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "templateId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ArchiveTemplate(w, r, templateId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTemplate operation middleware
func (siw *ServerInterfaceWrapper) GetTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId TemplateId

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", chi.URLParam(r, "templateId"), &templateId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "templateId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTemplate(w, r, templateId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SaveTemplate operation middleware
func (siw *ServerInterfaceWrapper) SaveTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId TemplateId

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", chi.URLParam(r, "templateId"), &templateId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "templateId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SaveTemplate(w, r, templateId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTemplateVersions operation middleware
func (siw *ServerInterfaceWrapper) ListTemplateVersions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId TemplateId

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", chi.URLParam(r, "templateId"), &templateId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "templateId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTemplateVersions(w, r, templateId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTemplateVersion operation middleware
func (siw *ServerInterfaceWrapper) CreateTemplateVersion(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId TemplateId

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", chi.URLParam(r, "templateId"), &templateId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "templateId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTemplateVersion(w, r, templateId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTemplateVersion operation middleware
func (siw *ServerInterfaceWrapper) GetTemplateVersion(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId TemplateId

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", chi.URLParam(r, "templateId"), &templateId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "templateId", Err: err})
		return
	}

	// ------------- Path parameter "version" -------------
	var version TemplateVersionNumber

	err = runtime.BindStyledParameterWithOptions("simple", "version", chi.URLParam(r, "version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTemplateVersion(w, r, templateId, version)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bootstrap", wrapper.GetBootstrap)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orgs", wrapper.ListOrganizations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orgs", wrapper.CreateOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orgs/active", wrapper.SelectActiveOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orgs/invitations/{invitationID}/accept", wrapper.AcceptOrganizationInvitation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs", wrapper.ListRuns)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs/{runId}", wrapper.GetRun)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runs/{runId}/complete", wrapper.CompleteRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs/{runId}/items/{itemId}", wrapper.GetRunItem)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/runs/{runId}/items/{itemId}", wrapper.UpdateRunItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/subjects", wrapper.ListSubjects)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/subjects", wrapper.CreateSubject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/subjects/{subjectId}", wrapper.GetSubject)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/subjects/{subjectId}", wrapper.UpdateSubject)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/subjects/{subjectId}/archive", wrapper.ArchiveSubject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/subjects/{subjectId}/members", wrapper.ListSubjectMembers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/subjects/{subjectId}/members", wrapper.AddSubjectMember)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/subjects/{subjectId}/members/{userId}", wrapper.RemoveSubjectMember)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/subjects/{subjectId}/run-templates", wrapper.ListSubjectRunTemplates)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/subjects/{subjectId}/runs", wrapper.ListSubjectRuns)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/subjects/{subjectId}/runs", wrapper.CreateRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/templates", wrapper.ListTemplates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/templates", wrapper.CreateTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/templates/{templateId}", wrapper.ArchiveTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/templates/{templateId}", wrapper.GetTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/templates/{templateId}", wrapper.SaveTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/templates/{templateId}/versions", wrapper.ListTemplateVersions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/templates/{templateId}/versions", wrapper.CreateTemplateVersion)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/templates/{templateId}/versions/{version}", wrapper.GetTemplateVersion)
	})

	return r
}
