// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apiv1

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// AuthSuccessResponse defines model for AuthSuccessResponse.
type AuthSuccessResponse struct {
	CsrfToken string `json:"csrf_token"`

	// Redirect Chemin SPA post-login (org onboarding ou accueil)
	Redirect string `json:"redirect"`
	User     User   `json:"user"`
}

// BootstrapResponse defines model for BootstrapResponse.
type BootstrapResponse struct {
	Authenticated bool `json:"authenticated"`

	// CsrfToken Jeton CSRF à envoyer en header X-CSRF-Token sur les mutations
	CsrfToken string `json:"csrf_token"`

	// GithubOauthEnabled true si REVUES_GITHUB_CLIENT_ID/SECRET sont configurés
	GithubOauthEnabled bool `json:"github_oauth_enabled"`

	// Redirect Chemin SPA suggéré si déjà authentifié
	Redirect *string `json:"redirect,omitempty"`
	User     *User   `json:"user,omitempty"`
}

// CreateOrganizationRequest defines model for CreateOrganizationRequest.
type CreateOrganizationRequest struct {
	Name string `json:"name"`

	// Slug Optionnel — dérivé du nom si omis
	Slug *string `json:"slug,omitempty"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorBody `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status État de santé
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus État de santé
type HealthResponseStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	CsrfToken string `json:"csrf_token"`
	User      User   `json:"user"`
}

// Organization defines model for Organization.
type Organization struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`

	// Role Rôle org (owner|admin|member)
	Role           string  `json:"role"`
	Slug           string  `json:"slug"`
	UiRunLabel     *string `json:"ui_run_label,omitempty"`
	UiSubjectLabel *string `json:"ui_subject_label,omitempty"`
}

// OrganizationActionResponse defines model for OrganizationActionResponse.
type OrganizationActionResponse struct {
	Organization Organization `json:"organization"`

	// Redirect Chemin SPA après action (accueil)
	Redirect string `json:"redirect"`
}

// OrganizationInvitation defines model for OrganizationInvitation.
type OrganizationInvitation struct {
	CreatedAt        string `json:"created_at"`
	Id               int64  `json:"id"`
	OrgRole          string `json:"org_role"`
	OrganizationId   int64  `json:"organization_id"`
	OrganizationName string `json:"organization_name"`
}

// OrganizationListResponse defines model for OrganizationListResponse.
type OrganizationListResponse struct {
	// ActiveOrganizationId Org active sur la session (null si pending)
	ActiveOrganizationId *int64 `json:"active_organization_id"`

	// CanCreate true si l'utilisateur n'a encore aucune appartenance
	CanCreate bool `json:"can_create"`

	// DefaultOrganizationId Suggestion depuis cookie revues_last_org si membre
	DefaultOrganizationId *int64                   `json:"default_organization_id"`
	Invitations           []OrganizationInvitation `json:"invitations"`
	Organizations         []Organization           `json:"organizations"`

	// Redirect Chemin SPA suggéré selon le nombre d'orgs
	Redirect *string `json:"redirect,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName     string              `json:"display_name"`
	Email           openapi_types.Email `json:"email"`
	Password        string              `json:"password"`
	PasswordConfirm string              `json:"password_confirm"`
}

// SelectOrganizationRequest defines model for SelectOrganizationRequest.
type SelectOrganizationRequest struct {
	OrganizationId int64 `json:"organization_id"`
}

// User defines model for User.
type User struct {
	AvatarUrl   *string             `json:"avatar_url,omitempty"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          int64               `json:"id"`
	Login       string              `json:"login"`

	// Role Rôle global (admin|editor|reader)
	Role string `json:"role"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody = CreateOrganizationRequest

// SelectActiveOrganizationJSONRequestBody defines body for SelectActiveOrganization for application/json ContentType.
type SelectActiveOrganizationJSONRequestBody = SelectOrganizationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Connexion email + mot de passe
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Déconnexion
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// Inscription email + mot de passe
	// (POST /auth/register)
	PostAuthRegister(w http.ResponseWriter, r *http.Request)
	// Bootstrap session + CSRF
	// (GET /bootstrap)
	GetBootstrap(w http.ResponseWriter, r *http.Request)
	// Santé de l'API versionnée
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Utilisateur authentifié courant
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Organisations de l'utilisateur
	// (GET /orgs)
	ListOrganizations(w http.ResponseWriter, r *http.Request)
	// Créer une organisation (onboarding)
	// (POST /orgs)
	CreateOrganization(w http.ResponseWriter, r *http.Request)
	// Sélectionner / basculer l'organisation active
	// (POST /orgs/active)
	SelectActiveOrganization(w http.ResponseWriter, r *http.Request)
	// Accepter une invitation d'organisation
	// (POST /orgs/invitations/{invitationID}/accept)
	AcceptOrganizationInvitation(w http.ResponseWriter, r *http.Request, invitationID int64)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Connexion email + mot de passe
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Déconnexion
// (POST /auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Inscription email + mot de passe
// (POST /auth/register)
func (_ Unimplemented) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Bootstrap session + CSRF
// (GET /bootstrap)
func (_ Unimplemented) GetBootstrap(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Santé de l'API versionnée
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Utilisateur authentifié courant
// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Organisations de l'utilisateur
// (GET /orgs)
func (_ Unimplemented) ListOrganizations(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Créer une organisation (onboarding)
// (POST /orgs)
func (_ Unimplemented) CreateOrganization(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Sélectionner / basculer l'organisation active
// (POST /orgs/active)
func (_ Unimplemented) SelectActiveOrganization(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Accepter une invitation d'organisation
// (POST /orgs/invitations/{invitationID}/accept)
func (_ Unimplemented) AcceptOrganizationInvitation(w http.ResponseWriter, r *http.Request, invitationID int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBootstrap operation middleware
func (siw *ServerInterfaceWrapper) GetBootstrap(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBootstrap(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrganizations operation middleware
func (siw *ServerInterfaceWrapper) ListOrganizations(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrganizations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrganization operation middleware
func (siw *ServerInterfaceWrapper) CreateOrganization(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrganization(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SelectActiveOrganization operation middleware
func (siw *ServerInterfaceWrapper) SelectActiveOrganization(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SelectActiveOrganization(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptOrganizationInvitation operation middleware
func (siw *ServerInterfaceWrapper) AcceptOrganizationInvitation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "invitationID" -------------
	var invitationID int64

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", chi.URLParam(r, "invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "invitationID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptOrganizationInvitation(w, r, invitationID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bootstrap", wrapper.GetBootstrap)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orgs", wrapper.ListOrganizations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orgs", wrapper.CreateOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orgs/active", wrapper.SelectActiveOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orgs/invitations/{invitationID}/accept", wrapper.AcceptOrganizationInvitation)
	})

	return r
}
