// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

type AllowedEmail struct {
	OrganizationID int64
	Email          string
	Role           string
	CreatedAt      string
}

type Attachment struct {
	ID          int64
	RunItemID   int64
	Filename    string
	MimeType    string
	SizeBytes   int64
	StoragePath string
	CreatedAt   string
}

type ChecklistRun struct {
	ID                int64
	SubjectID         int64
	TemplateVersionID int64
	Status            string
	DueDate           *string
	ClosingNote       string
	CreatedBy         *int64
	StartedAt         *string
	CompletedAt       *string
	NotionUrl         string
	EvidenceCsvSha256 string
	CreatedAt         string
}

type ChecklistTemplate struct {
	ID             int64
	OrganizationID int64
	Name           string
	ArchivedAt     *string
	CreatedAt      string
}

type EmailDelivery struct {
	ID             int64
	OrganizationID *int64
	ToAddress      string
	Subject        string
	Body           string
	Attempts       int64
	NextAttemptAt  *string
	ExpiresAt      *string
	State          string
	LastError      *string
	CreatedAt      string
}

type Integration struct {
	ID              int64
	OrganizationID  int64
	Type            string
	Enabled         int64
	ConfigEncrypted []byte
	CreatedAt       string
	UpdatedAt       string
}

type IntegrationLink struct {
	ID            int64
	RunItemID     int64
	IntegrationID int64
	ExternalKey   string
	ExternalUrl   string
	CreatedAt     string
}

type Organization struct {
	ID                      int64
	Name                    string
	Slug                    string
	UiSubjectLabel          string
	UiRunLabel              string
	LeadsMayAssignTeams     int64
	LeadsMayInviteMembers   int64
	LeadsMayInviteExternals int64
	CreatedAt               string
	CreatedBy               *int64
}

type OrganizationInvitation struct {
	ID             int64
	Email          string
	OrganizationID int64
	OrgRole        string
	CreatedAt      string
}

type OrganizationMember struct {
	OrganizationID int64
	UserID         int64
	Role           string
	CreatedAt      string
}

type OrganizationTeam struct {
	ID             int64
	OrganizationID int64
	Name           string
	Slug           string
	Description    string
	CreatedAt      string
}

type RunItem struct {
	ID           int64
	RunID        int64
	SourceItemID *int64
	Section      string
	Position     int64
	Label        string
	HelpText     string
	Required     int64
	Status       string
	Comment      string
	AssignedTo   *int64
	CheckedBy    *int64
	CheckedAt    *string
	UpdatedAt    string
}

type RunItemEvent struct {
	ID        int64
	RunItemID int64
	UserID    *int64
	OldStatus *string
	NewStatus string
	Comment   string
	CreatedAt string
}

type Session struct {
	ID             int64
	TokenHash      string
	UserID         int64
	OrganizationID *int64
	ExpiresAt      string
	CreatedAt      string
}

type Setting struct {
	OrganizationID int64
	Key            string
	ValueEncrypted []byte
	UpdatedAt      string
}

type Subject struct {
	ID             int64
	OrganizationID int64
	Name           string
	Description    string
	Visibility     string
	ArchivedAt     *string
	CreatedAt      string
	UpdatedAt      string
}

type SubjectDomain struct {
	SubjectID int64
	Tag       string
}

type SubjectMember struct {
	SubjectID int64
	UserID    int64
	Role      string
	CreatedAt string
}

type SubjectTag struct {
	SubjectID int64
	Tag       string
}

type TeamMember struct {
	TeamID    int64
	UserID    int64
	CreatedAt string
}

type TeamSubjectRole struct {
	TeamID    int64
	SubjectID int64
	Role      string
	GrantedBy *int64
	CreatedAt string
}

type TemplateDomain struct {
	TemplateID int64
	Tag        string
}

type TemplateItem struct {
	ID        int64
	VersionID int64
	Section   string
	Position  int64
	Label     string
	HelpText  string
	Required  int64
}

type TemplateVersion struct {
	ID          int64
	TemplateID  int64
	Version     int64
	PublishedAt string
	CreatedBy   *int64
}

type User struct {
	ID           int64
	GithubID     *int64
	Login        string
	Email        string
	DisplayName  string
	AvatarUrl    string
	Role         string
	PasswordHash string
	CreatedAt    string
	LastLoginAt  *string
}

type WebhookDelivery struct {
	ID         int64
	EventID    string
	EventType  string
	Url        string
	StatusCode *int64
	Success    int64
	CreatedAt  string
}
