// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package sqlc

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, organization_id, expires_at, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	TokenHash      string
	UserID         int64
	OrganizationID *int64
	ExpiresAt      string
	CreatedAt      string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.OrganizationID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT user_id, organization_id
FROM sessions
WHERE token_hash = ? AND expires_at > ?
`

type GetSessionByTokenHashParams struct {
	TokenHash string
	ExpiresAt string
}

type GetSessionByTokenHashRow struct {
	UserID         int64
	OrganizationID *int64
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, arg.TokenHash, arg.ExpiresAt)
	var i GetSessionByTokenHashRow
	err := row.Scan(&i.UserID, &i.OrganizationID)
	return i, err
}

const updateSessionOrganization = `-- name: UpdateSessionOrganization :execrows
UPDATE sessions SET organization_id = ?
WHERE token_hash = ? AND expires_at > ?
`

type UpdateSessionOrganizationParams struct {
	OrganizationID *int64
	TokenHash      string
	ExpiresAt      string
}

func (q *Queries) UpdateSessionOrganization(ctx context.Context, arg UpdateSessionOrganizationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSessionOrganization, arg.OrganizationID, arg.TokenHash, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
