// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"
)

const createLocalUser = `-- name: CreateLocalUser :execlastid
INSERT INTO users (github_id, login, email, display_name, avatar_url, role, password_hash, created_at, last_login_at)
VALUES (NULL, ?, ?, ?, '', ?, ?, ?, ?)
`

type CreateLocalUserParams struct {
	Login        string
	Email        string
	DisplayName  string
	Role         string
	PasswordHash string
	CreatedAt    string
	LastLoginAt  *string
}

func (q *Queries) CreateLocalUser(ctx context.Context, arg CreateLocalUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createLocalUser,
		arg.Login,
		arg.Email,
		arg.DisplayName,
		arg.Role,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.LastLoginAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, github_id, login, email, display_name, avatar_url, role
FROM users
WHERE lower(email) = lower(?)
`

type GetUserByEmailRow struct {
	ID          int64
	GithubID    *int64
	Login       string
	Email       string
	DisplayName string
	AvatarUrl   string
	Role        string
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Login,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Role,
	)
	return i, err
}

const getUserByGitHubID = `-- name: GetUserByGitHubID :one
SELECT id, github_id, login, email, display_name, avatar_url, role
FROM users
WHERE github_id = ?
`

type GetUserByGitHubIDRow struct {
	ID          int64
	GithubID    *int64
	Login       string
	Email       string
	DisplayName string
	AvatarUrl   string
	Role        string
}

func (q *Queries) GetUserByGitHubID(ctx context.Context, githubID *int64) (GetUserByGitHubIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByGitHubID, githubID)
	var i GetUserByGitHubIDRow
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Login,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Role,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, login, email, display_name, avatar_url, role
FROM users
WHERE id = ?
`

type GetUserByIDRow struct {
	ID          int64
	GithubID    *int64
	Login       string
	Email       string
	DisplayName string
	AvatarUrl   string
	Role        string
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Login,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Role,
	)
	return i, err
}

const getUserCredentialsByEmail = `-- name: GetUserCredentialsByEmail :one
SELECT id, github_id, login, email, display_name, avatar_url, role, password_hash
FROM users
WHERE lower(email) = lower(?)
`

type GetUserCredentialsByEmailRow struct {
	ID           int64
	GithubID     *int64
	Login        string
	Email        string
	DisplayName  string
	AvatarUrl    string
	Role         string
	PasswordHash string
}

func (q *Queries) GetUserCredentialsByEmail(ctx context.Context, lower string) (GetUserCredentialsByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserCredentialsByEmail, lower)
	var i GetUserCredentialsByEmailRow
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Login,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Role,
		&i.PasswordHash,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, github_id, login, email, display_name, avatar_url, role
FROM users
ORDER BY lower(login) ASC, id ASC
`

type ListUsersRow struct {
	ID          int64
	GithubID    *int64
	Login       string
	Email       string
	DisplayName string
	AvatarUrl   string
	Role        string
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.GithubID,
			&i.Login,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchLastLogin = `-- name: TouchLastLogin :exec
UPDATE users SET last_login_at = ? WHERE id = ?
`

type TouchLastLoginParams struct {
	LastLoginAt *string
	ID          int64
}

func (q *Queries) TouchLastLogin(ctx context.Context, arg TouchLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, touchLastLogin, arg.LastLoginAt, arg.ID)
	return err
}

const upsertGitHubUser = `-- name: UpsertGitHubUser :exec
INSERT INTO users (github_id, login, email, display_name, avatar_url, role, password_hash, created_at, last_login_at)
VALUES (?, ?, ?, ?, ?, ?, '', ?, ?)
ON CONFLICT(github_id) DO UPDATE SET
    login = excluded.login,
    email = excluded.email,
    display_name = excluded.display_name,
    avatar_url = excluded.avatar_url,
    role = excluded.role,
    last_login_at = excluded.last_login_at
`

type UpsertGitHubUserParams struct {
	GithubID    *int64
	Login       string
	Email       string
	DisplayName string
	AvatarUrl   string
	Role        string
	CreatedAt   string
	LastLoginAt *string
}

func (q *Queries) UpsertGitHubUser(ctx context.Context, arg UpsertGitHubUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertGitHubUser,
		arg.GithubID,
		arg.Login,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Role,
		arg.CreatedAt,
		arg.LastLoginAt,
	)
	return err
}
